### ISSUE TITLE
Writing of the files to a share fails

### ISSUE THREAD

**Issue by jsdhasfedssad** [mpgn/BackupOperatorToDA#2]
Hi. Your tool looks promising. However, at the moment it does not fully work for me.

I setup a share in Kali (10.0.0.220) using Impacket. I have tried both SMB1 and SMB2 but the issue occurs in both cases. When using SMB2 I also get an error message suggesting your tool does not support that.

<img width="287" alt="kali" src="https://user-images.githubusercontent.com/97032878/154425847-453e7e57-efda-463d-9842-f9a92d8e9790.png">

I then execute your tool from a domain-joined Windows 10 machine against a DC (Server 2019, 10.0.0.200) using the account domainuser1 which is a low priv. user but which is a member of the Backup Operators group. The result is that the SAM file is written to the share but then the tool fails. Comparing the size of the SAM file copy to the original file it seems the file is fully written meaning the error occurs after writing that. 

<img width="628" alt="windows" src="https://user-images.githubusercontent.com/97032878/154426156-58004eb4-6b1d-47ff-855f-1e4f954ffc97.png">

If I instead choose to dump the files to a folder locally on the DC it works. However, that is not really usefull during pentesting.

<img width="573" alt="working" src="https://user-images.githubusercontent.com/97032878/154427051-f64876e3-f7b1-4c8e-962e-2fc27be2868b.png">

**Comment by mpgn** [comment]
Try with option `-smb2support` on impacket :)

**Comment by jsdhasfedssad** [comment]
Unfortunately that does not work either. I mentioned that here initially. Here are related screenshots.

![kali2](https://user-images.githubusercontent.com/97032878/154445424-129e7041-8231-428b-b64f-1d572708231b.png)

![windows2](https://user-images.githubusercontent.com/97032878/154445466-8ed68b3a-b8c4-4862-a012-32a3a3bef2f6.png)

I get a different error from your tool and using SMB2 not even the SAM file is written to the share...

**Comment by mpgn** [comment]
double check the permission of your share folder, make sure everyone can write into it

**Comment by jsdhasfedssad** [comment]
Great! Using Impacket 0.9.24 this works. Good. Any plans to support authentication with NTLM hashes? And perhaps also to not need to have Microsoft Visual C++ installed to execute your binary?
